version: 1

update_configs:
  - package_manager: python
    directory: "/"
    update_schedule: live
    default_labels:
      - dependencies
    default_reviewers:
      - goodevilgenius
    target_branch: devel
